require:
  - rubocop-rails
  - rubocop-graphql
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1.2
  SuggestExtensions: false
  Exclude:
    - bin/**
    - db/migrate/**
    - db/schema.rb

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

GraphQL/FieldDescription:
  Enabled: false

GraphQL/ArgumentDescription:
  Enabled: false

GraphQL/ObjectDescription:
  Enabled: false